name: Build

# команда для запуска
on:
  pull_request:
    # любой брэнч
    branches:
      '*'
  push:
    branches:
      'main'

# описываем действия
jobs:
  test:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'gradle'
      - run: ./gradlew clean build

