name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      # устанавливаем Android SDK для запуска эмулятора и прогона на нем наших тестов
      # Download & install the Android SDK.
      # asd
      - uses: malinskiy/action-android/install-sdk@release/0.1.3
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
        with:
          cmd: ./gradlew connectedCheck
          api: 29
          tag: default
          abi: x86

# - uses - это скрипт, который что-то делает

# - run: ./gradlew clean build - для билда
# - run: ./gradlew clean connectedCheck - для запуска тестов